import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import { redirect } from "next/navigation"
import { Logo } from "@/components/ui/logo"
import Link from "next/link"
import { PrintControls } from "./print-trigger"

export default async function ExportPdfPage() {
  const session = await getServerSession(authOptions)
  if (!session || session.user.role === "EMPLOYEE") {
    redirect("/dashboard")
  }

  const role = session.user.role
  let goals

  if (role === "MANAGER") {
    const employees = await db.user.findMany({ where: { managerId: session.user.id } })
    const empIds = employees.map(e => e.id)
    goals = await db.goal.findMany({
      where: { employeeId: { in: empIds } },
      include: { employee: { select: { name: true, email: true } }, checkins: true },
      orderBy: { createdAt: "desc" },
    })
  } else {
    goals = await db.goal.findMany({
      include: { employee: { select: { name: true, email: true } }, checkins: true },
      orderBy: { createdAt: "desc" },
    })
  }

  // Calculate high-level summary metrics
  const totalGoalsCount = goals.length
  const statusCounts = goals.reduce((acc, g) => {
    acc[g.status] = (acc[g.status] || 0) + 1
    return acc
  }, {} as Record<string, number>)

  const approvedGoals = goals.filter(g => g.status === "APPROVED" || g.status === "LOCKED")
  const avgProgress = approvedGoals.length > 0
    ? Math.round(approvedGoals.reduce((sum, g) => {
        const goalCheckins = g.checkins
        if (goalCheckins.length === 0) return sum
        // Calculate max achievement progress
        const maxAchievement = Math.max(...goalCheckins.map(c => c.achievement))
        const progressPct = g.target > 0 ? (maxAchievement / g.target) * 100 : 0
        return sum + Math.min(Math.max(progressPct, 0), 100)
      }, 0) / approvedGoals.length)
    : 0

  const reportDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  })

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 p-8 font-sans">
      <PrintControls role={role} />
      
      {/* 🛡️ Print-Only Custom Style Block */}
      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          body {
            background-color: #ffffff !important;
            color: #0f172a !important;
            padding: 0 !important;
          }
          .no-print {
            display: none !important;
          }
          .print-container {
            border: none !important;
            box-shadow: none !important;
            padding: 0 !important;
            background: transparent !important;
            max-width: 100% !important;
            width: 100% !important;
          }
          .page-break-avoid {
            page-break-inside: avoid;
          }
          tr {
            page-break-inside: avoid;
          }
        }
        @page {
          size: A4 landscape;
          margin: 1.2cm;
        }
      `}} />

      {/* 📄 Main Printable Report Paper Container */}
      <div className="print-container max-w-7xl mx-auto bg-white p-10 rounded-3xl border border-slate-200/60 shadow-xl shadow-slate-100/50">
        
        {/* 🏢 Corporate Header */}
        <div className="flex items-start justify-between border-b border-slate-100 pb-8 mb-8">
          <div>
            <Logo size={42} showText={true} animate={false} />
            <h1 className="text-2xl font-black tracking-tight text-slate-900 mt-6">
              Enterprise Achievement & Goal Report
            </h1>
            <p className="text-sm font-medium text-slate-500 mt-1">
              Generated by {session.user.name} ({role})
            </p>
          </div>
          <div className="text-right">
            <span className="text-[10px] font-bold tracking-wider text-indigo-600 bg-indigo-50 px-3 py-1.5 rounded-full uppercase">
              {role} REPORT
            </span>
            <p className="text-xs font-semibold text-slate-500 mt-4">Report Date</p>
            <p className="text-sm font-bold text-slate-900">{reportDate}</p>
          </div>
        </div>

        {/* 📊 Summary Metrics Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          <div className="p-4 rounded-2xl border border-slate-100 bg-slate-50/50">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Total Goals</span>
            <p className="text-2xl font-black text-slate-900">{totalGoalsCount}</p>
          </div>
          <div className="p-4 rounded-2xl border border-slate-100 bg-slate-50/50">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Avg org progress</span>
            <p className="text-2xl font-black text-indigo-600">{avgProgress}%</p>
          </div>
          <div className="p-4 rounded-2xl border border-slate-100 bg-slate-50/50">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Approved/Locked</span>
            <p className="text-2xl font-black text-emerald-600">
              {Number(statusCounts["APPROVED"] || 0) + Number(statusCounts["LOCKED"] || 0)}
            </p>
          </div>
          <div className="p-4 rounded-2xl border border-slate-100 bg-slate-50/50">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Pending/Rejected</span>
            <p className="text-2xl font-black text-amber-600">
              {Number(statusCounts["SUBMITTED"] || 0) + Number(statusCounts["REJECTED"] || 0) + Number(statusCounts["DRAFT"] || 0)}
            </p>
          </div>
        </div>

        {/* 📝 Goals Ledger Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b-2 border-slate-200 text-slate-400 font-bold uppercase tracking-wider">
                <th className="py-3.5 px-3">Employee</th>
                <th className="py-3.5 px-3">Goal Details</th>
                <th className="py-3.5 px-3">Thrust Area</th>
                <th className="py-3.5 px-3 text-right">Target</th>
                <th className="py-3.5 px-3 text-right">Weight</th>
                <th className="py-3.5 px-3 text-center">Status</th>
                <th className="py-3.5 px-3 text-center">Q1</th>
                <th className="py-3.5 px-3 text-center">Q2</th>
                <th className="py-3.5 px-3 text-center">Q3</th>
                <th className="py-3.5 px-3 text-center">Q4</th>
                <th className="py-3.5 px-3 text-right">Progress</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {goals.map((goal) => {
                // Calculate actual progress percentage
                const goalCheckins = goal.checkins
                const maxAchievement = goalCheckins.length > 0 
                  ? Math.max(...goalCheckins.map(c => c.achievement))
                  : 0
                const progressPct = goal.target > 0 ? Math.round((maxAchievement / goal.target) * 100) : 0
                const constrainedProgress = Math.min(Math.max(progressPct, 0), 100)

                // Build quarter values map
                const qValues: Record<string, number> = {}
                goalCheckins.forEach(c => {
                  qValues[c.quarter] = c.achievement
                })

                return (
                  <tr key={goal.id} className="hover:bg-slate-50/50 transition-colors">
                    {/* Employee Info */}
                    <td className="py-3.5 px-3">
                      <p className="font-bold text-slate-900">{goal.employee.name}</p>
                      <p className="text-[10px] text-slate-500 font-medium">{goal.employee.email}</p>
                    </td>
                    {/* Goal Title */}
                    <td className="py-3.5 px-3 max-w-xs">
                      <p className="font-semibold text-slate-800 leading-snug">{goal.title}</p>
                    </td>
                    {/* Thrust Area */}
                    <td className="py-3.5 px-3 font-medium text-slate-500">
                      {goal.thrustArea || "General"}
                    </td>
                    {/* Target & UoM */}
                    <td className="py-3.5 px-3 text-right font-semibold text-slate-700 whitespace-nowrap">
                      {goal.target} <span className="text-[10px] text-slate-400 font-normal">{goal.uom}</span>
                    </td>
                    {/* Weightage */}
                    <td className="py-3.5 px-3 text-right font-bold text-slate-900">
                      {goal.weightage}%
                    </td>
                    {/* Status */}
                    <td className="py-3.5 px-3 text-center">
                      <span className={`inline-block text-[9px] font-extrabold uppercase px-2 py-0.5 rounded-full ${
                        goal.status === "APPROVED" ? "bg-emerald-50 text-emerald-700 border border-emerald-100" :
                        goal.status === "LOCKED" ? "bg-indigo-50 text-indigo-700 border border-indigo-100" :
                        goal.status === "REJECTED" ? "bg-rose-50 text-rose-700 border border-rose-100" :
                        goal.status === "SUBMITTED" ? "bg-amber-50 text-amber-700 border border-amber-100" :
                        "bg-slate-100 text-slate-600 border border-slate-200"
                      }`}>
                        {goal.status}
                      </span>
                    </td>
                    {/* Quarters (Q1 - Q4) */}
                    <td className="py-3.5 px-3 text-center font-medium text-slate-600">
                      {qValues["Q1"] !== undefined ? qValues["Q1"] : "-"}
                    </td>
                    <td className="py-3.5 px-3 text-center font-medium text-slate-600">
                      {qValues["Q2"] !== undefined ? qValues["Q2"] : "-"}
                    </td>
                    <td className="py-3.5 px-3 text-center font-medium text-slate-600">
                      {qValues["Q3"] !== undefined ? qValues["Q3"] : "-"}
                    </td>
                    <td className="py-3.5 px-3 text-center font-medium text-slate-600">
                      {qValues["Q4"] !== undefined ? qValues["Q4"] : "-"}
                    </td>
                    {/* Progress Bar & Pct */}
                    <td className="py-3.5 px-3 text-right whitespace-nowrap">
                      <div className="inline-flex items-center gap-2">
                        <span className="font-extrabold text-slate-900">{constrainedProgress}%</span>
                        <div className="w-12 h-1.5 bg-slate-100 rounded-full overflow-hidden no-print">
                          <div 
                            className={`h-full rounded-full ${
                              constrainedProgress === 100 ? "bg-emerald-500" :
                              constrainedProgress > 50 ? "bg-indigo-500" :
                              "bg-amber-500"
                            }`}
                            style={{ width: `${constrainedProgress}%` }}
                          />
                        </div>
                      </div>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>

        {/* 🏢 Footer Signature Block */}
        <div className="page-break-avoid border-t border-slate-100 mt-12 pt-8 flex items-center justify-between text-[10px] text-slate-400">
          <p>CONFIDENTIAL · FOR INTERNAL ATOMBERG ENTERPRISE GOAL ALIGNMENT ONLY</p>
          <p>© {new Date().getFullYear()} MYGoals Portal. All rights reserved.</p>
        </div>

      </div>
    </div>
  )
}
